# Secret for Azure SQL Server DB
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.dbSecret.name }}
type: Opaque
data:
  MSSQL_PASSWORD: {{ .Values.dbSecret.password }}

---

# Scaler For Azure Function
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .Values.scaledObject.name }}
spec:
  scaleTargetRef:
    name: azure-function-deployment
  pollingInterval: {{ .Values.scaledObject.pollingInterval }}
  maxReplicaCount: {{ .Values.scaledObject.maxReplicaCount }}
  minReplicaCount: {{ .Values.scaledObject.minReplicaCount }}
  triggers:
  - type: mssql
    metadata:
      username: {{ .Values.scaledObject.database.username }}
      passwordFromEnv: MSSQL_PASSWORD
      host: {{ .Values.scaledObject.database.host }}
      database: {{ .Values.scaledObject.database.dbName }}
      query: {{ .Values.scaledObject.database.query }}
      targetValue: {{ .Values.scaledObject.database.targetValue | quote }}

---

# Function Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-function-deployment
  labels: 
    app: {{ .Values.function1.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.function1.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.function1.name }}
    spec:
      containers:
        - image: {{ .Values.function1.image }}
          name: {{ .Values.function1.name }}
          ports:
          - containerPort: {{ .Values.function1.containerPort }}
          env:
          - name: MSSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.dbSecret.name }}
                key: MSSQL_PASSWORD       

---

# Function Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.function1.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.function1.port }}
      targetPort: {{ .Values.function1.containerPort }}
      nodePort: {{ .Values.function1.nodePort }}
